# Use root/example as user/password credentials
version: "3.1"

services:
  entrance-server:
    container_name: "entrance-server"
    build: .

    ports:
      - "3500:3500"
    entrypoint: "node index"
