# Use root/example as user/password credentials
version: "3.1"

services:
  entrance-server:
    container_name: "entrance-server"
    build: .
    depends_on:
      - database
    ports:
      - "3500:3500"
    entrypoint: "node index"

  database:
    container_name: "mongoe"
    image: balnacska/coachdb
    restart: always
    ports:
      - 27017:27017
